### PR TITLE
Add option to specify device when in a single GPU setup

### PR DESCRIPTION
**Pull request by gordicaleksa**
Useful for running multiple single GPU experiments in parallel (using this for mup experiments).

### CODE REVIEW

**Comment by ngc92** [comment]
`export CUDA_VISIBLE_DEVICES=1`  :)

**Comment by karpathy** [comment]
I think I prefer using `CUDA_VISIBLE_DEVICES`, less code footprint?

**Comment by gordicaleksa** [comment]
I don't think that will work? we hardcode device 0 in our code? @karpathy @ngc92

**Comment by ngc92** [comment]
AFAIK, the numbers correspond to available devices, but I'm not 100% sure

**Comment by karpathy** [comment]
@gordicaleksa it will work, if it's anything like what i did before with PyTorch. I do this all the time on PyTorch when I do sweeps.

**Comment by karpathy** [comment]
Will close for now and bring back in case the CUDA_VISIBLE_DEVICES doesn't work.

**Comment by gordicaleksa** [comment]
@karpathy it doesn't work just tested, we should add this option for people who want to run multiple runs and schedule them across specified devices.

**Pull request closed without merging**
