### PR TITLE
MFU for other GPUs

### PR DESCRIPTION
**Pull request by ngc92**
extrapolating from spec sheets, yay :)

### CODE REVIEW

**Review by rosslwheeler — COMMENTED** [review]
@ngc92 - the A5500 should be 1665 like you mentioned?

**Comment by ngc92** [comment]
numbers for the workstation Ampere GPUs currently don't make sense, I get > 100%.

**Comment by chinthysl** [comment]
Nice, I manually adjusted for H100 using the datasheet.

**Comment by karpathy** [comment]
Merged to master, made a new file llmc/mfu.h, adjusted the code so that we don't use fancy features so also Windows doesn't break.

**Pull request merged**
