### PR TITLE
Testability

### PR DESCRIPTION
**Pull request by ngc92**
Towards having our CI actually _test_ our code.
@rosslwheeler I just added the commands to run, I guess there is some more config needed to ensure this runs on GPU runners

### CODE REVIEW

**Comment by rosslwheeler** [comment]
@ngc92 Will fix the above and try the run and let you know of any changes.

**Comment by rosslwheeler** [comment]
@ngc92 fixed the tests and it all runs/passes with your changes.

**Comment by karpathy** [comment]
This is the "actually run code" CI right? which is great. But it seems to still be draft and is failing, is there more intended functionality?

**Comment by rosslwheeler** [comment]
@karpathy - yes, I have a separate PR for this which includes your suggestions as well. This will include the GPU so we'll need to set the runner up on your GitHub account. I'm just waiting on ubicloud to get your invite/account set up.

**Comment by ngc92** [comment]
This PR actually enables testing the recomputation modes, and fixes an error with them.

**Pull request merged**
