### PR TITLE
Adding the example kernels to CI

### PR DESCRIPTION
**Pull request by Ricardicus**
Might as well build the example kernels up here in the CI!

### CODE REVIEW

**Comment by rosslwheeler** [comment]
@Ricardicus - there was a discussion a few days ago and they wanted to keep those Makefile lines in there for visibility. I assume that might still be the case?

**Comment by Ricardicus** [comment]
Oh ok! I has missed that. What kind of visibility? I think the names of the files are pretty good. This doesn't change what gets built and what not. I can leave the makefile as it is if it was a philosophy behind it..

**Comment by Ricardicus** [comment]
If we want some kind of explanation of the translation units in there, maybe we should add a Readme under there instead of putting that doc in makefile

**Comment by Ricardicus** [comment]
If we want some kind of explanation of the translation units in there, my suggestion is that we add a Readme here under instead of putting that doc in the makefile. The comments in the makefile I removed group the files in forward and backward pass, but the files already have _backward and _forward in them.

**Comment by Ricardicus** [comment]
... and there is no wildcard *.cu being built, only the targets defined in the TARGETS variable (expanded in the all:) decides what gets built and what not..

**Comment by karpathy** [comment]
I'm ok adding these to CI I think, but I wouldn't remove them from Makefile. There are great reasons to want to use these locally during dev. How long does this compile for / how much time does it add to CI

**Comment by Ricardicus** [comment]
All of them are still in the makefile, they are still built. It can check the time it took.

**Comment by rosslwheeler** [comment]
@Ricardicus - can you build them in CI with make -j?

**Comment by Ricardicus** [comment]
Oh that would speed it up considerably ... can fiddle with it when i get back.. also; the reason i changed the makefile was because i considered some lines as unnecessary. This change does not change the makefiles functionality . The case for leaving these lines would be to make the makefile a bit more explanatory (with the comments)

**Comment by Ricardicus** [comment]
I removed the changes to the Makefile and I added a -j4 that makes the build step faster.

**Pull request merged**
