### PR TITLE
Autodetect GPU compute capability using nvidia-smi.

### PR DESCRIPTION
**Pull request by akulchik**
Resolves karpathy/llm.c#387

### CODE REVIEW

**Comment by rosslwheeler** [comment]
@akulchik - what toolkit version are you using and what OS?  The change looks fine but interested to understand what version of the Cuda toolkit does not have the device query file. It's in 12.4 which is the current toolkit.

**Comment by akulchik** [comment]
@rosslwheeler I use Ubuntu 22.04 on WSL 2. Funny, because I have indeed CUDA 12.4 installed.
```
$ nvidia-smi --version
NVIDIA-SMI version  : 550.76.01
NVML version        : 550.76
DRIVER version      : 552.22
CUDA Version        : 12.4
```

**Comment by rosslwheeler** [comment]
Interesting – am running WSL2 as well. My version is slightly newer and below are the binaries from the Windows bin directory. Maybe the device file is really new? Seems like there would have been a lot of complaints if so but not sure. Your change is likely better/safer but interested in knowing if there’s something else going on too. I'm wondering if you upgrade to 12.4.1 whether the file will show up? Also, previously - generic installation or did you do a custom one? Will check with Nvidia support on this. Thanks for the info.

nvidia-smi --version
NVIDIA-SMI version  : 551.78
NVML version        : 551.78
DRIVER version      : 551.78
CUDA Version        : 12.4

And here’s the bin directory of 12.4 on Windows:

-a----         3/28/2024   4:06 AM       13564416 nvcc.exe
-a----         3/28/2024   4:06 AM       334 nvcc.profile
-a----         3/15/2024   3:46 PM       50694656 nvdisasm.exe
-a----         3/15/2024   3:47 PM       749056 nvfatbin_120_0.dll
-a----         3/15/2024   3:47 PM       38247424 nvJitLink_120_0.dll
-a----         3/15/2024   4:01 PM        4913152 nvjpeg64_12.dll
-a----         3/28/2024   4:06 AM       19965440 nvlink.exe
-a----         3/15/2024   4:01 PM        2207744 nvprof.exe
-a----         3/15/2024   3:46 PM        254464 nvprune.exe
-a----         3/15/2024   3:46 PM        5367808 nvrtc-builtins64_124.dll
-a----         3/15/2024   3:46 PM       44738048 nvrtc64_120_0.dll
-a----         3/15/2024   4:25 PM       129 nvvp.bat
-a----         3/28/2024   4:06 AM       19582976 ptxas.exe
-a----         3/28/2024   4:06 AM        84480 __nvcc_device_query.exe

**Comment by akulchik** [comment]
Ok, I will try to install the latest SDK version and let you know the results, thanks.

**Pull request closed without merging**
