### PR TITLE
Add to .gitignore: fp32 binaries, *.exe, *.obj, .venv

### PR DESCRIPTION
**Pull request by dagelf**
Has anyone ever had any issues just ignoring .*?

Also added minimal msvc ignores.

### CODE REVIEW

**Comment by karpathy** [comment]
I don't love ignoring .* and then exceptioning things. Scared for that strategy.

**Comment by dagelf** [comment]
I'm sure you have good reason, would love to know why!

I have researched it and not found much written about it. IMHO .* are hidden because you don't really want to see them. 

Seems so much cleaner than having a lot of lines in .gitignore?

I personally don't care about it because I don't use vscode and all the addons, yet...  but having tried it, I can see the appeal of having a good .gitignore and being able to run `git status`.

**Comment by dagelf** [comment]
But the '!.gitignore' looks ugly... so for aesthetical reasons... I can see that!

**Comment by dagelf** [comment]
Closes #202

**Pull request merged**
