### PR TITLE
Building on Windows

### PR DESCRIPTION
**Pull request by azret**
Minimum set of support files to build on Windows. Use build_msvc.bat in a Visual Studio Command x64 Prompt to build with MSVC.

See #19 for some comments re /fp:fast and /O

https://github.com/karpathy/llm.c/issues/19#issuecomment-2053990872

### CODE REVIEW

**Comment by rosslwheeler** [comment]
@azret - thanks but there are still some other changes needed to support OpenMP 5.2. Will create a new PR for this per comments in https://github.com/karpathy/llm.c/pull/118

**Comment by azret** [comment]
> OpenMP

Yeah. We'll need add the Open ML option as well. For now just copy this files locally and add it in the build_msvc.bat.

I'll add the CUDA build scripts later tomorrow. (For now in Visual Studio create a new CUDA project and add the needed files)

**Comment by rosslwheeler** [comment]
@azret - the changes are in the PR already. Just creating a smaller version. Thanks.

**Comment by dagelf** [comment]
Is `\dev\win` referenced in the batch file an official `msvc` path?

**Comment by azret** [comment]
Closing this. See #19

**Pull request closed without merging**
