### PR TITLE
Adding a github workflow

### PR DESCRIPTION
**Pull request by Ricardicus**
This is a start, but this workflow does the following:

- builds and tests on CPU with and without openMP (macos and ubuntu)
- builds the CUDA files (does not test them)

Ideally one would like to test the CUDA also, but it is hard to do this.
I think it would be possible to use the virtual GPU drivers from NVIDIA, but I don't know
how to do this and I think that rabit hole can be left uninvestigated for now. This is a start!

It will run on PRs and pushes to the master branch.

### CODE REVIEW

**Comment by Ricardicus** [comment]
This PR includes the fix presented in this PR:

https://github.com/karpathy/llm.c/pull/208

So If you want to merge this, then you can forget about PR #208

**Comment by Ricardicus** [comment]
Here is a link to the logs of how this workflow was running on my fork:
https://github.com/Ricardicus/llm.c/actions/runs/8776172376

**Comment by karpathy** [comment]
very cool, let's test it out!

**Comment by Ricardicus** [comment]
Yey!

**Pull request merged**
