### PR TITLE
add edu fineweb support, with 10B and 100B version

### PR DESCRIPTION
**Pull request by eliebak**
Adding edu-fineweb support https://huggingface.co/datasets/HuggingFaceFW/fineweb-edu

How to use it : 
for 10B : `python fineweb.py -t "edu" -v "10B"`
for 100B : `python fineweb.py -t "edu" -v "100B"`

And in the launching script: 
```
-i "dev/data/fineweb10B/edu_fineweb_train_*.bin" \
-j "dev/data/fineweb10B/edu_fineweb_val_*.bin" \
```

### CODE REVIEW

**Comment by karpathy** [comment]
Wow, this is amazing! I'll take a look today. So we probably want to hard switch to this, at our scale. If you're not training more than a few T epochs you'd always want to use this it looks like?

**Comment by karpathy** [comment]
If the results in the huggingface page are true we might as well hard switch to that, forget if statements

**Comment by eliebak** [comment]
Yes, i think the best thing is switching to fineweb-edu and also doing arc evals (or other reasoning task) instead of hellaswag. 

Screenshot 2024-06-02 at 19 18 50

**Comment by karpathy** [comment]
Ah yes ok so we'll actually see a regression but it's because we don't measure properly :D
At some point you do have to decide on what eval domains you care about, and cater the pretraining mix to that.

**Comment by eliebak** [comment]
Yes, that's why I think it's worth keeping the if statement even if it's a bit messy for now. When we have a proper way to evaluate the model, we can suppress them, right?

**Comment by cometyang** [comment]
@eliebak, I tried to run train both 124M model on Fineweb and Finewebedu, the HellaSwag result does not improved while validation error get better.  Have you observed the same thing?
https://github.com/karpathy/llm.c/discussions/580#discussioncomment-9789323

**Pull request merged**
