### PR TITLE
Fix incorrect GPU assignment in multi gpu setup

### PR DESCRIPTION
**Pull request by chinthysl**
Fix for #369

### CODE REVIEW

**Comment by rosslwheeler** [comment]
Check out this PR - works fine on WSL2 Ubuntu 22.04. Thanks for the fix!

**Comment by pjj** [comment]
This fix works on my end for the small/default gpt2 model (2.1m tok/s on 8 GPU).

The current code still breaks for the gpt2-xl model, albeit in a different way, unrelated to openMPI (with 1 GPU or 8GPU).  The error I'm getting is: 
```1373: void matmul_backward(floatX*, floatX*, floatX*, floatX*, floatX*, floatX*, float*, int, int, int, int): Assertion `(OC % OC_per_warp) == 0' failed.``` 

Commit 6c179fa works fine for gpt2-xl.  It is possible that a separate independent bug was introduced since that commit that only breaks the larger model.

**Comment by karpathy** [comment]
Confirm this fixes the issue, stepping at ~460K tok/s on 4XA100 GPUs.

**Comment by pjj** [comment]
I've verified that the fix by ademeure works on my end for GPT2-XL and opened a PR.

**Pull request merged**
