### PR TITLE
Minor correction for openmp check

### PR DESCRIPTION
**Pull request by Ricardicus**
Hi,

Amazing project :D 

Thank you! 

I needed this to work for my mac, I didnt have omp

### CODE REVIEW

**Comment by karpathy** [comment]
oh, yeah, oops. I see the need for the guard around omp.h import. Is the other part in Makefile necessary?

**Comment by karpathy** [comment]
(referring to the preprocessor absence, ok).

**Comment by XiaoConstantine** [comment]
I think removing ` -Xpreprocessor ` actually break the check of proper installation of `libomp`

**Comment by Ricardicus** [comment]
The reason I removed the -Xpreprocessor, was that it was always returning 0 even if openmp wasn't installed.

```   
$ echo |clang -Xpreprocessor -fopenmp -x c -E -;echo $?
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 401 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2

0
``` 
I got a consistent negative response without it:
``` 
$ echo |clang -fopenmp -x c -E -;echo $? 
clang: error: unsupported option '-fopenmp'
1
``` 

It seems like installing libomp with brew install libomp is not enough on my mac.
My clang compiler still complains about -fopenmp.

If I pass -Xclang or -Xpreprocessor to the -fopenmp flag it is silenced. However,
I don't think openmp is used in that case. 

On my linux, I can compile with libopenmp using gcc.. 

Perhaps change CC to gcc ?

**Comment by Ricardicus** [comment]
I included something that I think works on both my mac and on Linux.
It combines the original check, with a more basic directory check on mac.
There seems to be something different between the clang I use on Linux and the one in Mac, where
-fopenmp passed directly to clang creates a problem; but passing it via the -Xclang argument makes it work.
I don't know why this is, but I try to get around it here:
https://github.com/karpathy/llm.c/pull/14

**Comment by Ricardicus** [comment]
I included something that works on both my mac and on Linux.
It combines the original check, with a more basic directory check on mac.
There seems to be something different between the clang I use on Linux and the one in Mac, where
-fopenmp passed directly to clang creates a problem; but passing it via the -Xclang argument makes it work.
I don't know why this is, but I try to get around it in a new PR here: https://github.com/karpathy/llm.c/pull/14

**Comment by XiaoConstantine** [comment]
> The reason I removed the -Xpreprocessor, was that it was always returning 0 even if openmp wasn't installed.
> 
> ```
> $ echo |clang -Xpreprocessor -fopenmp -x c -E -;echo $?
> # 1 "<stdin>"
> # 1 "<built-in>" 1
> # 1 "<built-in>" 3
> # 401 "<built-in>" 3
> # 1 "<command line>" 1
> # 1 "<built-in>" 2
> # 1 "<stdin>" 2
> 
> 0
> ```
> 
> I got a consistent negative response without it:
> 
> ```
> $ echo |clang -fopenmp -x c -E -;echo $? 
> clang: error: unsupported option '-fopenmp'
> 1
> ```
> 
> It seems like installing libomp with brew install libomp is not enough on my mac. My clang compiler still complains about -fopenmp.
> 
> If I pass -Xclang or -Xpreprocessor to the -fopenmp flag it is silenced. However, I don't think openmp is used in that case.
> 
> On my linux, this check works and I can compile with libopenmp still. Maybe there is some issue with the standard clang included in mac and openmp? On Linux this is not an issue, and this check works there.
> 
> edit: Using -Xclang on mac actually works and openmp is included. However, there is an inconsistency here where the -X argument is not needed on Linux.

Thanks! I noticed the same behavior with `-Xpreprocessor` as well, evaluate result is always `0`, similarly when removing it , always evaluate to `1`.

On my m3 pro (with clang 15.0.0), I also noticed that following behavior:
```bash
 ${CC:-cc} -fopenmp -x c -E - > /dev/null 2>&1; echo $?
1
```

```bash
 ${CC:-cc} -Xpreprocessor -fopenmp -x c -E - > /dev/null 2>&1; echo $?


```
(this will hang)

seems related to clang

**Pull request merged**
