### PR TITLE
Added the .gitignore file.

### PR DESCRIPTION
**Pull request by this-is-batman**
- This will help in keeping the working tree clean.
- All the .bin files and the /data/ folder have been added to gitignore.

### CODE REVIEW

**Comment by this-is-batman** [comment]
Fixes https://github.com/karpathy/llm.c/issues/43

**Comment by this-is-batman** [comment]
Athough I realise this is not a necessary thing to do, and we can ignore this most of the time, this helps keep a clean working directory. I have tried to keep only the basic things in the .gitignore file.

**Comment by davmacario** [comment]
What do you think about adding entries for commonly ignored files?
Something along the lines of [this](https://github.com/github/gitignore/blob/main/Python.gitignore).

**Comment by this-is-batman** [comment]
> What do you think about adding entries for commonly ignored files? Something along the lines of [this](https://github.com/github/gitignore/blob/main/Python.gitignore).

This looks good, but I prefer to keep a small gitignore file, and improve upon it as the project matures.

**Pull request closed without merging**
