### PR TITLE
Adding GPU CI workflow file

### PR DESCRIPTION
**Pull request by rosslwheeler**
@karpathy - will need you to hook up your repo (if you haven't already). This should fail since it will try to get a GPU runner that your repo does not have access to (yet). Once the GPU runner is hooked up - you can re-run this workflow to see if it passes.

Thanks to Ubicloud and Nvidia for the help and for sponsoring this.

### CODE REVIEW

**Comment by Ricardicus** [comment]
Just checking in to see where this project is going and noticed you managed to get this cuda tests running as a CI. Really cool! Good job! 

How does it work, does Ubicloud work with GitHub in some special way to give these runners special hardware access? It isn't virtualization, it is running on Nvidia hardware right? Nice that projects like this gets a sponsorship for it also.

**Comment by rosslwheeler** [comment]
Hey! Yes, I believe it's running on Nvidia hardware direct - A4000 Ada cards. Super easy to setup. If you're interested, I would reach out to Ubicloud here: https://www.ubicloud.com. If you're on a private repo, their runners are much cheaper than GitHub.

**Comment by Ricardicus** [comment]
Nice! Thank you for the info 😊

**Comment by furkansahin** [comment]
Hey @Ricardicus , I am a founding engineer at Ubicloud. We have all kinds of runners including GPU ones :) Is there any way we can help you? You can reach more information here https://www.ubicloud.com/use-cases/github-actions or directly reach me from furkan[at]ubicloud[dot]com.
Best

**Pull request merged**
