### PR TITLE
Makefile windows support

### PR DESCRIPTION
**Pull request by rosslwheeler**
Updating for latest Makefile changes

### CODE REVIEW

**Comment by karpathy** [comment]
I see there's quite a bit of activity on this PR still, is it ready to merge?

**Comment by rosslwheeler** [comment]
@karpathy - yes, let's do it.

**Comment by rosslwheeler** [comment]
@karpathy - thanks - I have a window-readme.md for this Makefile and other Windows support in my fork. What would like to do with this readme?

**Comment by karpathy** [comment]
depends on its length. if too long, i'd hide it into doc/ and link to it from main README. if very short, ok to include in main README

**Comment by rosslwheeler** [comment]
Right now it's long. Will link it here later today for you to take a look.

**Comment by rosslwheeler** [comment]
@karpathy - here's the link to the readme:

https://github.com/rosslwheeler/llm.c/blob/windows-readme/doc/windows/windows_README.md

Put in the doc/ directory? Don't really have a preference....

**Pull request merged**
