### PR TITLE
Generalize MFU logic to common non-A100 GPUs

### PR DESCRIPTION
**Pull request by gordicaleksa**
I've added support for some common GPUs.

I can refactor it a bit if you think that repeating this computation after every training step is unnecessary (which it is it's a tradeoff but it's a few cycles on the CPU).

We could instead call it once somewhere in the beginning of the main func and later just pass the promised flops into mfu func. I wanted to keep everything in the same place so made a tradeoff for readability.

### CODE REVIEW

**Comment by ngc92** [comment]
have you  seen this?
https://github.com/karpathy/llm.c/pull/486
currently stalled, because getting the actual expected MFU is apparently quite nontrivial. E.g., are we looking at bf16 with fp32 accumulate or with bf16 accumulate (makes a difference for some cards).

**Comment by gordicaleksa** [comment]
Oops, no i haven't! Thanks for flagging!

TBH given that our goal is to have everything in a single file i wouldn't try to be exhaustive here, let's just list the most common GPUs and let people tweak if they need it (similar to how GPT-2 hyperparams are hardcoded).

wdyt?

**Comment by ngc92** [comment]
I don't think we'd actually put this into the main file in the end. The main intention of the other PR was to have some very basic performance data coded into the file, and then be able to extrapolate across a wide range of GPUs.

**Comment by karpathy** [comment]
Yep we'll hide this somewhere, imminently I think. Sounds like we should close this one and merge @ngc92 PR https://github.com/karpathy/llm.c/pull/486

**Comment by karpathy** [comment]
Merged an adjusted https://github.com/karpathy/llm.c/pull/486 just now, closing.

**Pull request closed without merging**
