### PR TITLE
WikiText103 eval, attempt to reproduce Alec table posted on Reddit

### PR DESCRIPTION
**Pull request by karpathy**
I get:

```
gpt2-124M nll: 3.058462142944336, ppl: 21.294784545898438
```

And we're supposed to get
https://www.reddit.com/r/MachineLearning/comments/oye64h/comment/h7ucco2/

i.e. 1.17 (in what i assume is the nll), so we're not even close to the right order of magnitude.

### CODE REVIEW

**Comment by karpathy** [comment]
my own failed attempt at https://github.com/karpathy/llm.c/issues/246

**Comment by joeshmoe0112358** [comment]
> i.e. 1.17 (in what i assume is the nll), so we're not even close to the right order of magnitude.

The formatting of the table is broken, if you look at the leftmost column it says WikiText-2 but gives the number of parameters for the model. I believe the columns should be shifted one to the right with wikitext scores in the range of 20 - 40.

**Comment by karpathy** [comment]
@joeshmoe0112358 ohhh that makes sense RE: column names 🤦‍♂️ . But ok, I am getting ppl ~21 here, and Alec is citing 37.5 for this model

**Comment by julianjfouf** [comment]
Yes, I am highly skeptical of the accuracy of Alec's table because 37.50 is exactly what the GPT-2 paper reports and they used very different methods. Also, if Alec really did evaluate with stride length = 32, then we would expect his numbers to be significantly lower than the paper's, where lower is better for perplexity (e.g. [check highlighted text](https://huggingface.co/docs/transformers/en/perplexity#:~:text=When%20we%20run%20the%20above%20with%20stride%20%3D%201024%2C%20i.e.%20no%20overlap%2C%20the%20resulting%20PPL%20is%2019.44%2C%20which%20is%20about%20the%20same%20as%20the%2019.93%20reported%20in%20the%20GPT%2D2%20paper.%20By%20using%20stride%20%3D%20512%20and%20thereby%20employing%20our%20striding%20window%20strategy%2C%20this%20jumps%20down%20to%2016.45.)).

**Comment by joeshmoe0112358** [comment]
Yes, I am highly skeptical of the reliability of Alec's table because 37.50 is exactly what the GPT-2 paper reports and they used very different methods. Also, if Alec really did evaluate with stride length = 32, then we would expect his numbers to be significantly lower than the paper's, where lower is better for perplexity. (e.g. [check highlighted text](https://huggingface.co/docs/transformers/perplexity#:~:text=When%20we%20run%20the%20above%20with%20stride%20%3D%201024%2C%20i.e.%20no%20overlap%2C%20the%20resulting%20PPL%20is%2019.44%2C%20which%20is%20about%20the%20same%20as%20the%2019.93%20reported%20in%20the%20GPT%2D2%20paper.%20By%20using%20stride%20%3D%20512%20and%20thereby%20employing%20our%20striding%20window%20strategy%2C%20this%20jumps%20down%20to%2016.45.))

**Comment by karpathy** [comment]
We are abandoning WikiText103 because it's a total mess. We'll instead look at one/few of ARC Easy / Challenge, Squad, Hellaswag, TriviaQA, LAMBADA. Closing.

**Pull request closed without merging**
