### PR TITLE
Initial mojo version

### PR DESCRIPTION
**Pull request by chadbrewbaker**
@dorjeduck - I had to fix MOJO_PYTHON_LIBRARY - made a note in the Readme. I also changed the relative paths.  Anything else you want?

### CODE REVIEW

**Comment by dorjeduck** [comment]
> @dorjeduck - I had to fix MOJO_PYTHON_LIBRARY - made a note in the Readme. I also changed the relative paths. Anything else you want?

just dont open a pull request with my source code yet, its not ready. Let me improve on it and i will do when ready. Thx

**Comment by karpathy** [comment]
I don't think I'll merge mojo code to this repo, I don't have the bandwidth to support it. I will be very happy to link to it, similar to how I linked to friend repos in llama2.c repo. Very eager to see the port though!

**Comment by dorjeduck** [comment]
Hey Andrej, thanks for being aware of it. I don't see it in your repo either, and its just not ready anyway, its a Mojo beginner code. I am discussing within the Mojo Discord community how to move forward with it, there are surely people much more skilled in Mojo than me. At one point we hopefully have an elegant and performant Mojo port, coming along with proper benchmarking etc. No point looking to close right. Love all your work and wisdom sharing, thanks for all that.

**Comment by karpathy** [comment]
Please use a Discussion instead of a PR/Issue.
Very eager to see Mojo port (and other languages!) of llm.c

**Pull request closed without merging**
